SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Coupon` CASCADE
;

DROP TABLE IF EXISTS `Discount` CASCADE
;

DROP TABLE IF EXISTS `Plan_Type` CASCADE
;

DROP TABLE IF EXISTS `Product` CASCADE
;

DROP TABLE IF EXISTS `Product_Category` CASCADE
;

DROP TABLE IF EXISTS `Product_Level` CASCADE
;

DROP TABLE IF EXISTS `Product_Services` CASCADE
;

DROP TABLE IF EXISTS `Service_Master` CASCADE
;

DROP TABLE IF EXISTS `Subscription_Plan` CASCADE
;

DROP TABLE IF EXISTS `Subscription_Plan_Prod` CASCADE
;


SET FOREIGN_KEY_CHECKS=1
; 
