logging.level:
  org.springframework.web: DEBUG
  org.springframework.security: DEBUG


spring:
    application:
        name: edulab-sgfm-dev-service-prometheus
    http:
        log-request-details: true
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
    datasource:
        url: jdbc:mysql://localhost:3306/subscription?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: begusarai
        initialization-mode: always
        platform: mysql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

 
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
 
host: http://localhost:8080

  